export const EXPENSE_CATEGORIES = [
  { id: "food", text: "餐饮", icon: "🍽️" },
  { id: "drink", text: "饮料", icon: "☕" },
  { id: "dessert", text: "零食", icon: "🧁" },
  { id: "fruit", text: "水果", icon: "🍎" },
  { id: "shopping", text: "购物", icon: "🛍️" },
  { id: "children", text: "孩子", icon: "👶" },
  { id: "transport", text: "交通", icon: "🚗" },
  { id: "travel", text: "旅行", icon: "✈️" },
  { id: "home", text: "居家", icon: "🏠" },
  { id: "housing", text: "住房", icon: "🏘️" },
  { id: "car", text: "汽车", icon: "🚙" },
  { id: "communication", text: "通讯", icon: "📱" },
  { id: "medical", text: "医疗", icon: "🏥" },
  { id: "daily", text: "日用", icon: "🧴" },
  { id: "entertainment", text: "娱乐", icon: "🎮" },
  { id: "beauty", text: "美容", icon: "💄" },
  { id: "social", text: "社交", icon: "👥" },
  { id: "digital", text: "数码", icon: "📱" },
  { id: "book", text: "书籍", icon: "📚" },
  { id: "study", text: "学习", icon: "📖" },
  { id: "gift", text: "礼物", icon: "🎁" },
  { id: "office", text: "办公", icon: "💼" },
  { id: "parking", text: "车位费", icon: "🅿️" },
  { id: "water", text: "水费", icon: "💧" },
  { id: "electricity", text: "电费", icon: "⚡" },
  { id: "gas", text: "燃气费", icon: "🔥" },
];

export const INCOME_CATEGORIES = [
  { id: "salary", text: "工资", icon: "💰" },
  { id: "redPacket", text: "红包", icon: "🧧" },
  { id: "payment", text: "收款", icon: "💵" },
  { id: "dividend", text: "分红", icon: "📈" },
  { id: "rent", text: "租金", icon: "🏠" },
  { id: "refund", text: "退款", icon: "🔄" },
  { id: "bonus", text: "年终奖", icon: "🎉" },
  { id: "transfer", text: "转账", icon: "🔁" },
  { id: "financial", text: "理财", icon: "💹" },
  { id: "borrow", text: "借入", icon: "🤝" },
];
